services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL=postgresql://postgres:Nic/DH*!uM4QUF?@db.zutwdsfvttvkucqdikhe.supabase.co:5432/postgres
